NewData = [log(Data(:,13)),...
           Data(:,4),...
           log(Data(:,13)).^3,...
           Data(:,1).*log(Data(:,13)).^2,...
           Data(:,1),...
           Data(:,4).*log(Data(:,13)).^2,...
           Data(:,4).*log(Data(:,13)),...
           Data(:,1).*log(Data(:,13))];
       
TargetREG = MultiPolyRegress(NewData,R,1,'legend');